version: '2'
services:

  api-gateway:
    container_name: api-gateway
    image: api-gateway
    build: .
    ports:
      - "8080:8080"
#    volumes:
#    - ./config:/config
    network_mode: "projeto-aplicado"