version: '2'
services:

  registry-discovery:
    container_name: registry-discovery
    image: registry-discovery
    build: .
    ports:
      - "8081:8081"
#    volumes:
#    - ./config:/config
    network_mode: "projeto-aplicado"