version: '2'
services:

  pagamentodb:
    container_name: pagamentodb
    image: pagamentodb
    build: .
    ports:
      - "27017:27017"
#    volumes:
#    - ./config:/config
    network_mode: "projeto-aplicado"