version: '2'
services:

  cadastrodb:
    container_name: cadastrodb
    image: cadastrodb
    build: .
    ports:
      - "27017:27017"
#    volumes:
#    - ./config:/config
    network_mode: "projeto-aplicado"