version: '2'
services:

  pagamento:
    container_name: pagamento
    image: pagamento
    build: .
    ports:
      - "8086:8086"
#    volumes:
#    - ./config:/config
    network_mode: "projeto-aplicado"